language: python

python:
    - "2.7"

install:
    - pip install -e ./arteria -r ./arteria/requirements/dev
    - pip install -e ./runfolder -r ./runfolder/requirements/dev

script:
    - ./unittests

notifications:
    email: false
