# Default configuration file for bcl2fastq

---

# TODO Ensure all these mappings are correctly setup.
bcl2fastq:
  versions:
    2.16.0.10:
      binary: /usr/local/bin/bcl2fastq
      class_creation_function:  _get_bcl2fastq2x_runner
    1.8.4:
      binary: /path/to/bcl2fastq
      class_creation_function: _get_bcl2fastq1x_runner

machine_type:
  HiSeq X:
    bcl2fastq_version: 2.16.0.10
  HiSeq 2500:
    bcl2fastq_version: 1.8.4
  HiSeq 2000:
    bcl2fastq_version: 1.8.4
  NextSeq 500:
    bcl2fastq_version: 1.8.4
  HiSeq 4000:
    bcl2fastq_version: 1.8.4
  MiSeq:
    bcl2fastq_version: 1.8.4


runfolder_path: /bcl2fastq-ws/tmp_test_data
default_output_path: /tmp

bcl2fastq_logs_path: /var/log/bcl2fastq_logs